// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    QDate: typeof import('quasar')['QDate']
    QIcon: typeof import('quasar')['QIcon']
    QImg: typeof import('quasar')['QImg']
    QInput: typeof import('quasar')['QInput']
    QPage: typeof import('quasar')['QPage']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
