// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarEdit: typeof import('./components/AvatarEdit.vue')['default']
    ChangePassword: typeof import('./components/ChangePassword.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    FileUploader: typeof import('./components/FileUploader.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    OneSignalStatus: typeof import('./components/OneSignalStatus.vue')['default']
    ProfileEdit: typeof import('./components/ProfileEdit.vue')['default']
    QAvatar: typeof import('quasar')['QAvatar']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardActions: typeof import('quasar')['QCardActions']
    QCardSection: typeof import('quasar')['QCardSection']
    QIcon: typeof import('quasar')['QIcon']
    QImg: typeof import('quasar')['QImg']
    QInput: typeof import('quasar')['QInput']
    QPage: typeof import('quasar')['QPage']
    QSelect: typeof import('quasar')['QSelect']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
